# Basic Python

## 1. Split this string

In [18]:
s = "Hi there Sam!"

In [19]:
print(s.split(" "))

['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [16]:
planet = "Earth"
diameter = 12742

In [17]:
print("The diameter of {} is {} Kilometers".format(planet, diameter))

The diameter of Earth is 12742 Kilometers


## 3. In this nest dictionary grab the word "hello"

In [14]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [15]:
d['k1'][3]['tricky'][3]['target'][3]

'hello'

# Numpy

In [1]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [2]:
array = np.zeros(10)

In [3]:
farray = np.ones(10)*5

## 5. Create an array of all the even integers from 20 to 35

In [12]:
array = []
for i in range(20, 36):
  if i % 2 == 0:
    array.append(i)
print(array)

[20, 22, 24, 26, 28, 30, 32, 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [4]:
temp =  np.arange(0, 9).reshape(3,3)
print(temp)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [5]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.concatenate([a,b]))

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [6]:
import pandas as pd
import random

In [8]:
temp = np.random.randint(10, size=(3,2))
print(pd.DataFrame(temp))

   0  1
0  7  3
1  1  6
2  9  1


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [9]:
import datetime
test_date = datetime.datetime.strptime("01-1-2023", "%d-%m-%Y")
data = pd.date_range(test_date, periods=10)
print(data.strftime("%d-%m-%Y"))

Index(['01-01-2023', '02-01-2023', '03-01-2023', '04-01-2023', '05-01-2023',
       '06-01-2023', '07-01-2023', '08-01-2023', '09-01-2023', '10-01-2023'],
      dtype='object')


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [10]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [11]:
df = pd.DataFrame(lists, columns =['ID', 'name', 'balance']) 
print(df)

   ID name  balance
0   1  aaa       22
1   2  bbb       25
2   3  ccc       24
